### ISSUE TITLE
Is Go language mandatory?

### ISSUE THREAD

**Issue by barenko** [lana/backend-challenge#1]
Both below sentences in [README.md](https://github.com/lana/backend-challenge/blob/master/README.md) are contraditory: 

`Aside from the programming language, we're not defining anything else as mandatory.`

`Don't agree with the programming language? Use another one!`

**Comment by vsmoraes** [comment]
Yes, Go is mandatory for completing the challenge. I've push an update to the README.md to address this.

Thanks for the feedback, @barenko!
